//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABMC_RACTE_CONTROLE
    {
        public int ID { get; set; }
        public int ID_EMP { get; set; }
        public int ID_EST { get; set; }
        public string INFCTE_ID { get; set; }
        public string INFCTE_VERSAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public string STATUS { get; set; }
        public string CNPJ_EMIT_CTE { get; set; }
        public string NOME_EMIT_CTE { get; set; }
        public Nullable<int> IDE_NCT { get; set; }
        public Nullable<System.DateTime> IDE_DHEMI { get; set; }
    }
}
