//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_ENTREGA
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_ENTREGA_CNPJ { get; set; }
        public string INFNFE_ENTREGA_CPF { get; set; }
        public string INFNFE_ENTREGA_XLGR { get; set; }
        public string INFNFE_ENTREGA_NRO { get; set; }
        public string INFNFE_ENTREGA_XCPL { get; set; }
        public string INFNFE_ENTREGA_XBAIRRO { get; set; }
        public int INFNFE_ENTREGA_CMUN { get; set; }
        public string INFNFE_ENTREGA_XMUN { get; set; }
        public string INFNFE_ENTREGA_UF { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
