//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_AVULSA
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_AVULSA_CNPJ { get; set; }
        public string INFNFE_AVULSA_XORGAO { get; set; }
        public string INFNFE_AVULSA_MATR { get; set; }
        public string INFNFE_AVULSA_XAGENTE { get; set; }
        public int INFNFE_AVULSA_FONE { get; set; }
        public string INFNFE_AVULSA_UF { get; set; }
        public string INFNFE_AVULSA_NDAR { get; set; }
        public System.DateTime INFNFE_AVULSA_DEMI { get; set; }
        public decimal INFNFE_AVULSA_VDAR { get; set; }
        public string INFNFE_AVULSA_REPEMI { get; set; }
        public Nullable<System.DateTime> INFNFE_AVULSA_DPAG { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
