//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_CANA_DEDUC
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_CANA_DEDUC_XDED { get; set; }
        public Nullable<decimal> INFNFE_CANA_DEDUC_VDED { get; set; }
        public Nullable<decimal> INFNFE_CANA_DEDUC_VFOR { get; set; }
        public Nullable<decimal> INFNFE_CANA_DEDUC_VTOTDED { get; set; }
        public Nullable<decimal> INFNFE_CANA_DEDUC_VLIQFOR { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
