//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_INF_ADIC_OBSFISCO
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_INFADIC_OBSFISCO_XCAMPO { get; set; }
        public string INFNFE_INFADIC_OBSFISCO_XTEXTO { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
