//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_DEST
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_DEST_CNPJ { get; set; }
        public string INFNFE_DEST_CPF { get; set; }
        public string INFNFE_DEST_XNOME { get; set; }
        public string INFNFE_DEST_ENDERDEST_XLGR { get; set; }
        public string INFNFE_DEST_ENDERDEST_NRO { get; set; }
        public string INFNFE_DEST_ENDERDEST_XCPL { get; set; }
        public string INFNFE_DEST_ENDERDEST_XBAIRRO { get; set; }
        public int INFNFE_DEST_ENDERDEST_CMUN { get; set; }
        public string INFNFE_DEST_ENDERDEST_XMUN { get; set; }
        public string INFNFE_DEST_ENDERDEST_UF { get; set; }
        public Nullable<int> INFNFE_DEST_ENDERDEST_CEP { get; set; }
        public string INFNFE_DEST_ENDERDEST_CPAIS { get; set; }
        public string INFNFE_DEST_ENDERDEST_XPAIS { get; set; }
        public Nullable<int> INFNFE_DEST_ENDERDEST_FONE { get; set; }
        public decimal INFNFE_DEST_IE { get; set; }
        public string INFNFE_DEST_ISUF { get; set; }
        public string INFNFE_DEST_EMAIL { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public string INFNFE_DEST_IDESTRANGEIRO { get; set; }
        public string INFNFE_DEST_INDIEDEST { get; set; }
        public string INFNFE_DEST_IM { get; set; }
    }
}
