//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_IMP_COFINS
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public Nullable<int> TAG_COFINSALIQ_CST { get; set; }
        public Nullable<decimal> TAG_COFINSALIQ_VBC { get; set; }
        public Nullable<decimal> TAG_COFINSALIQ_PCOFINS { get; set; }
        public Nullable<decimal> TAG_COFINSALIQ_VCOFINS { get; set; }
        public Nullable<int> TAG_COFINSQTDE_CST { get; set; }
        public Nullable<decimal> TAG_COFINSQTDE_QBCPROD { get; set; }
        public Nullable<decimal> TAG_COFINSQTDE_VALIQPRO { get; set; }
        public Nullable<decimal> TAG_COFINSQTDE_VCOFINS { get; set; }
        public Nullable<int> TAG_COFINSNT_CST { get; set; }
        public Nullable<int> TAG_COFINSOUTR_CST { get; set; }
        public Nullable<decimal> TAG_COFINSOUTR_VBC { get; set; }
        public Nullable<decimal> TAG_COFINSOUTR_PCOFINS { get; set; }
        public Nullable<decimal> TAG_COFINSOUTR_QBCPROD { get; set; }
        public Nullable<decimal> TAG_COFINSOUTR_VALIQPROD { get; set; }
        public Nullable<decimal> TAG_COFINSOUTR_VCOFINS { get; set; }
        public Nullable<decimal> TAG_COFINSST_VBC { get; set; }
        public Nullable<decimal> TAG_COFINSST_PCOFINS { get; set; }
        public Nullable<decimal> TAG_COFINSST_QBCPROD { get; set; }
        public Nullable<decimal> TAG_COFINSST_VALIQPROD { get; set; }
        public Nullable<decimal> TAG_COFINSST_VCOFINS { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
