//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_EMIT
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_EMIT_CNPJ { get; set; }
        public string INFNFE_EMIT_CPF { get; set; }
        public string INFNFE_EMIT_XNOME { get; set; }
        public string INFNFE_EMIT_XFANT { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_XLGR { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_NRO { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_XCPL { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_XBAIRRO { get; set; }
        public Nullable<int> INFNFE_EMIT_ENDEREMIT_CMUN { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_XMUN { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_UF { get; set; }
        public Nullable<int> INFNFE_EMIT_ENDEREMIT_CEP { get; set; }
        public Nullable<int> INFNFE_EMIT_ENDEREMIT_CPAIS { get; set; }
        public string INFNFE_EMIT_ENDEREMIT_XPAIS { get; set; }
        public Nullable<decimal> INFNFE_EMIT_ENDEREMIT_FONE { get; set; }
        public string INFNFE_EMIT_IE { get; set; }
        public string INFNFE_EMIT_IEST { get; set; }
        public string INFNFE_EMIT_IM { get; set; }
        public string INFNFE_EMIT_CNAE { get; set; }
        public Nullable<int> INFNFE_EMIT_CRT { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
