//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_IMP_ICMS
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public string TAG_GRUPO { get; set; }
        public Nullable<int> TAG_ORIG { get; set; }
        public Nullable<int> TAG_CST { get; set; }
        public Nullable<int> TAG_CSOSN { get; set; }
        public Nullable<int> TAG_MODBC { get; set; }
        public Nullable<decimal> TAG_PREDBC { get; set; }
        public Nullable<decimal> TAG_VBC { get; set; }
        public Nullable<decimal> TAG_PICMS { get; set; }
        public Nullable<decimal> TAG_VICMS { get; set; }
        public Nullable<int> TAG_MODBCST { get; set; }
        public Nullable<decimal> TAG_PMVAST { get; set; }
        public Nullable<decimal> TAG_PREDBCST { get; set; }
        public Nullable<decimal> TAG_VBCST { get; set; }
        public Nullable<decimal> TAG_PICMSST { get; set; }
        public Nullable<decimal> TAG_VICMSST { get; set; }
        public string TAG_UFST { get; set; }
        public Nullable<decimal> TAG_PBCOP { get; set; }
        public Nullable<decimal> TAG_VBCSTRET { get; set; }
        public Nullable<decimal> TAG_VICMSSTRET { get; set; }
        public Nullable<int> TAG_MOTDESICMS { get; set; }
        public Nullable<decimal> TAG_PCREDSN { get; set; }
        public Nullable<decimal> TAG_VCREDICMSSN { get; set; }
        public Nullable<decimal> TAG_VBCSTDEST { get; set; }
        public Nullable<decimal> TAG_VICMSSTDEST { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> TAG_VICMSDESON { get; set; }
        public Nullable<decimal> TAG_VICMSOP { get; set; }
        public Nullable<decimal> TAG_PDIF { get; set; }
        public Nullable<decimal> TAG_VICMSDIF { get; set; }
    }
}
