//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_COMBUST
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public int INFNFE_DET_PROD_COMB_CPRODANP { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_COMB_CODIF { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_COMB_QTEMP { get; set; }
        public string INFNFE_DET_PROD_COMB_UFCONS { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_CB_CD_QBCPROD { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_CB_CD_VALQPRD { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_CB_CD_VCIDE { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_COMB_PMIXGN { get; set; }
    }
}
