//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_ORIGEM_XML
    {
        public int ID { get; set; }
        public string VERSAO_NFE { get; set; }
        public string DESCRICAO { get; set; }
        public string TIPO_ACESSO { get; set; }
        public string WEB_URL_ACESSO { get; set; }
        public string WEB_FORNECEDOR { get; set; }
        public string DB_NOME_BASE { get; set; }
        public Nullable<int> DB_PORTA { get; set; }
        public string DB_URL { get; set; }
        public string FILE_DIR_READ { get; set; }
        public string FILE_DIR_BKP { get; set; }
        public string EMAIL_URL { get; set; }
        public string EMAIL_USER { get; set; }
        public string EMAIL_PWD { get; set; }
        public string EMAIL_PROTOCOLO { get; set; }
        public string EMAIL_PASTA_BKP { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public string EMAIL_PASTA { get; set; }
        public string PATH_CERTIFIED { get; set; }
        public string PWD_CERTIFIED { get; set; }
    }
}
