//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_TOTAIS
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VBC { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VICMS { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VBCST { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VST { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VPROD { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VFRETE { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VSEG { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VDESC { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VII { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VIPI { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VPIS { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VCOFINS { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VOUTRO { get; set; }
        public decimal INFNFE_TOTAL_ICMSTOT_VNF { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VSERV { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VBC { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VISS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VPIS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VCOFINS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VRETPIS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VRETCOFINS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VRETCSLL { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VBCIRRF { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VIRRF { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VBCRETPREV { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_RTRIB_VRETPREV { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ICMSTOT_VICMSDES { get; set; }
        public Nullable<System.DateTime> INFNFE_TOTAL_ISSQNTOT_DCOMPET { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VDEDUC { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VOUTRO { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VDESCIN { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VDESCC { get; set; }
        public Nullable<decimal> INFNFE_TOTAL_ISSQNTOT_VISSRET { get; set; }
        public string INFNFE_TOTAL_ISSQNTOT_CREGTRIB { get; set; }
    }
}
