//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int INFNFE_DET_NITEM { get; set; }
        public string INFNFE_DET_PROD_CPROD { get; set; }
        public string INFNFE_DET_PROD_CEAN { get; set; }
        public string INFNFE_DET_PROD_XPROD { get; set; }
        public string INFNFE_DET_PROD_NCM { get; set; }
        public string INFNFE_DET_PROD_EXTIPI { get; set; }
        public int INFNFE_DET_PROD_CFOP { get; set; }
        public string INFNFE_DET_PROD_UCOM { get; set; }
        public decimal INFNFE_DET_PROD_QCOM { get; set; }
        public decimal INFNFE_DET_PROD_VUNCOM { get; set; }
        public decimal INFNFE_DET_PROD_VPROD { get; set; }
        public string INFNFE_DET_PROD_CEANTRIB { get; set; }
        public string INFNFE_DET_PROD_UTRIB { get; set; }
        public decimal INFNFE_DET_PROD_QTRIB { get; set; }
        public decimal INFNFE_DET_PROD_VUNTRIB { get; set; }
        public decimal INFNFE_DET_PROD_VFRETE { get; set; }
        public decimal INFNFE_DET_PROD_VSEG { get; set; }
        public decimal INFNFE_DET_PROD_VDESC { get; set; }
        public decimal INFNFE_DET_PROD_VOUTRO { get; set; }
        public Nullable<int> INFNFE_DET_PROD_INDTOT { get; set; }
        public string INFNFE_DET_PROD_INFADPROD { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public string INFNFE_DET_PROD_XPED { get; set; }
        public Nullable<int> INFNFE_DET_PROD_NITEMPED { get; set; }
    }
}
