//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_TRANSP
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int INFNFE_TRANSP_MODFRETE { get; set; }
        public string INFNFE_TRANSP_VAGAO { get; set; }
        public string INFNFE_TRANSP_BALSA { get; set; }
        public string INFNFE_TRANSP_TRP_CNPJ { get; set; }
        public string INFNFE_TRANSP_TRP_CPF { get; set; }
        public string INFNFE_TRANSP_TRP_XNOME { get; set; }
        public string INFNFE_TRANSP_TRP_IE { get; set; }
        public string INFNFE_TRANSP_TRP_XENDER { get; set; }
        public string INFNFE_TRANSP_TRP_XMUN { get; set; }
        public string INFNFE_TRANSP_TRP_UF { get; set; }
        public Nullable<decimal> INFNFE_TRANSP_RTRP_VSERV { get; set; }
        public Nullable<decimal> INFNFE_TRANSP_RTRP_VBCRET { get; set; }
        public Nullable<decimal> INFNFE_TRANSP_RTRP_PICMSRET { get; set; }
        public Nullable<decimal> INFNFE_TRANSP_RTRP_VICMSRET { get; set; }
        public Nullable<int> INFNFE_TRANSP_RTRP_CFOP { get; set; }
        public Nullable<int> INFNFE_TRANSP_RTRP_CMUNFG { get; set; }
        public string INFNFE_TRANSP_RTRP_VTRP_PLACA { get; set; }
        public string INFNFE_TRANSP_RTRP_VTRP_UF { get; set; }
        public string INFNFE_TRANSP_RTRP_VTRP_RNTC { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
