//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_DI_ADI
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_DI { get; set; }
        public int INFNFE_DET_PROD_DI_ADI_NAD { get; set; }
        public int INFNFE_DET_PROD_DI_ADI_NSQA { get; set; }
        public string INFNFE_DET_PROD_DI_ADI_CFAB { get; set; }
        public Nullable<decimal> INFNFE_DET_PROD_DI_ADI_VDEDI { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
