//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_VEIC
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public int INFNFE_DET_PROD_VPROD_TPOP { get; set; }
        public string INFNFE_DET_PROD_VPROD_TCHASSI { get; set; }
        public string INFNFE_DET_PROD_VPROD_CCOR { get; set; }
        public string INFNFE_DET_PROD_VPROD_XCOR { get; set; }
        public string INFNFE_DET_PROD_VPROD_POT { get; set; }
        public string INFNFE_DET_PROD_VPROD_CILIN { get; set; }
        public string INFNFE_DET_PROD_VPROD_PESOL { get; set; }
        public string INFNFE_DET_PROD_VPROD_PESOB { get; set; }
        public string INFNFE_DET_PROD_VPROD_NSERIE { get; set; }
        public string INFNFE_DET_PROD_VPROD_TPCOMB { get; set; }
        public string INFNFE_DET_PROD_VPROD_NMOTOR { get; set; }
        public string INFNFE_DET_PROD_VPROD_CMT { get; set; }
        public string INFNFE_DET_PROD_VPROD_DIST { get; set; }
        public int INFNFE_DET_PROD_VPROD_ANOMOD { get; set; }
        public int INFNFE_DET_PROD_VPROD_ANOFAB { get; set; }
        public string INFNFE_DET_PROD_VPROD_TPPINT { get; set; }
        public int INFNFE_DET_PROD_VPROD_TPVEIC { get; set; }
        public int INFNFE_DET_PROD_VPROD_ESPVEIC { get; set; }
        public string INFNFE_DET_PROD_VPROD_VIN { get; set; }
        public int INFNFE_DET_PROD_VPROD_CONDVEIC { get; set; }
        public int INFNFE_DET_PROD_VPROD_CMOD { get; set; }
        public int INFNFE_DET_PROD_VPROD_CCORDEN { get; set; }
        public int INFNFE_DET_PROD_VPROD_LOTA { get; set; }
        public int INFNFE_DET_PROD_VPROD_TPREST { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
