//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_CONTROLE
    {
        public int ID { get; set; }
        public int ID_EMP { get; set; }
        public int ID_EST { get; set; }
        public string INFNFE_ID { get; set; }
        public decimal INFNFE_VERSAO { get; set; }
        public int INFNFE_IDE_CUF { get; set; }
        public string INFNFE_IDE_CNF { get; set; }
        public string INFNFE_IDE_CNOP { get; set; }
        public int INFNFE_IDE_INDPAG { get; set; }
        public string INFNFE_IDE_MOD { get; set; }
        public int INFNFE_IDE_SERIE { get; set; }
        public int INFNFE_IDE_NNF { get; set; }
        public System.DateTime INFNFE_IDE_DEMI { get; set; }
        public Nullable<System.DateTime> INFNFE_IDE_DSAIENT { get; set; }
        public Nullable<System.DateTime> INFNFE_IDE_HSAIENT { get; set; }
        public int INFNFE_IDE_TPNF { get; set; }
        public int INFNFE_IDE_CMUNFG { get; set; }
        public string INFNFE_IDE_NFR_RNFE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_CUF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_AAMM { get; set; }
        public string INFNFE_IDE_NFR_RNF_CNPJ { get; set; }
        public string INFNFE_IDE_NFR_RNF_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_SERIE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_NNF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_CUF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_AAMM { get; set; }
        public string INFNFE_IDE_NFR_RNFP_CNPJ { get; set; }
        public string INFNFE_IDE_NFR_RNFP_CPF { get; set; }
        public string INFNFE_IDE_NFR_RNFP_IE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_SERIE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_NNF { get; set; }
        public string INFNFE_IDE_NFR_RNFP_RCTE { get; set; }
        public string INFNFE_IDE_NFR_RNFP_RECF_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_RECF_NECF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_RECF_NCOO { get; set; }
        public Nullable<int> INFNFE_IDE_TPIMP { get; set; }
        public Nullable<int> INFNFE_IDE_TPEMIS { get; set; }
        public Nullable<int> INFNFE_IDE_CDV { get; set; }
        public Nullable<int> INFNFE_IDE_TPAMB { get; set; }
        public Nullable<int> INFNFE_IDE_FINNFE { get; set; }
        public Nullable<int> INFNFE_IDE_PROCEMI { get; set; }
        public string INFNFE_IDE_VERPROC { get; set; }
        public Nullable<System.DateTime> INFNFE_IDE_DHCONT { get; set; }
        public string INFNFE_IDE_XJUST { get; set; }
        public string CNPJ_EMIT_NFE { get; set; }
        public string NOME_EMIT_NFE { get; set; }
        public int ID_SOL_NFE { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public string INFNFE_IDE_IDDEST { get; set; }
        public string INFNFE_IDE_INDFINAL { get; set; }
        public string INFNFE_IDE_INDPRES { get; set; }
    }
}
