//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_IMP_PIS
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public Nullable<int> TAG_PISALIQ_CST { get; set; }
        public Nullable<decimal> TAG_PISALIQ_VBC { get; set; }
        public Nullable<decimal> TAG_PISALIQ_PPIS { get; set; }
        public Nullable<decimal> TAG_PISALIQ_VPIS { get; set; }
        public Nullable<int> TAG_PISQTDE_CST { get; set; }
        public Nullable<decimal> TAG_PISQTDE_QBCPROD { get; set; }
        public Nullable<decimal> TAG_PISQTDE_VALIQPROD { get; set; }
        public Nullable<decimal> TAG_PISQTDE_VPIS { get; set; }
        public Nullable<int> TAG_PISNT_CST { get; set; }
        public Nullable<int> TAG_PISOUTR_CST { get; set; }
        public Nullable<decimal> TAG_PISOUTR_VBC { get; set; }
        public Nullable<decimal> TAG_PISOUTR_PPIS { get; set; }
        public Nullable<decimal> TAG_PISOUTR_QBCPROD { get; set; }
        public Nullable<decimal> TAG_PISOUTR_VALIQPROD { get; set; }
        public Nullable<decimal> TAG_PISOUTR_VPIS { get; set; }
        public Nullable<decimal> TAG_PISST_VBC { get; set; }
        public Nullable<decimal> TAG_PISST_PPIS { get; set; }
        public Nullable<decimal> TAG_PISST_QBCPROD { get; set; }
        public Nullable<decimal> TAG_PISST_VALIQPROD { get; set; }
        public Nullable<decimal> TAG_PISST_VPIS { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
