//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_MEDIC
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public string INFNFE_DET_PROD_MED_NLOTE { get; set; }
        public decimal INFNFE_DET_PROD_MED_QLOTE { get; set; }
        public System.DateTime INFNFE_DET_PROD_MED_DFAB { get; set; }
        public System.DateTime INFNFE_DET_PROD_MED_DVAL { get; set; }
        public decimal INFNFE_DET_PROD_MED_VPMC { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
