//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_IMP_IPI
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public string TAG_CLENQ { get; set; }
        public string TAG_CNPJPROD { get; set; }
        public string TAG_CSELO { get; set; }
        public Nullable<int> TAG_QSELO { get; set; }
        public string TAG_CENQ { get; set; }
        public string TAG_IPITRIB_CST { get; set; }
        public Nullable<decimal> TAG_IPITRIB_VBC { get; set; }
        public Nullable<decimal> TAG_IPITRIB_QUNID { get; set; }
        public Nullable<decimal> TAG_IPITRIB_VUNID { get; set; }
        public Nullable<decimal> TAG_IPITRIB_PIPI { get; set; }
        public Nullable<decimal> TAG_IPITRIB_VIPI { get; set; }
        public string TAG_IPINT_CST { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
