//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_DI
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public string INFNFE_DET_PROD_DI_NDI { get; set; }
        public System.DateTime INFNFE_DET_PROD_DI_DDI { get; set; }
        public string INFNFE_DET_PROD_DI_XLOCDESEMB { get; set; }
        public string INFNFE_DET_PROD_DI_UFDESEMB { get; set; }
        public System.DateTime INFNFE_DET_PROD_DI_DDESEMB { get; set; }
        public string INFNFE_DET_PROD_DI_CEXPORTADOR { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public string INT_NFE_DET_PROD_DI_TPVIATRANS { get; set; }
        public Nullable<decimal> INT_NFE_DET_PROD_DI_VAFRMM { get; set; }
        public string INFNFE_DET_PROD_DI_TPINTERMED { get; set; }
        public string INT_NFE_DET_PROD_DI_CNPJ { get; set; }
        public string INT_NFE_DET_PROD_DI_UFTERCEIRO { get; set; }
    }
}
