//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_NOTA_REFER
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public string INFNFE_IDE_NFR_RNFE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_CUF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_AAMM { get; set; }
        public string INFNFE_IDE_NFR_RNF_CNPJ { get; set; }
        public string INFNFE_IDE_NFR_RNF_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_SERIE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNF_NNF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_CUF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_AAMM { get; set; }
        public string INFNFE_IDE_NFR_RNFP_CNPJ { get; set; }
        public string INFNFE_IDE_NFR_RNFP_CPF { get; set; }
        public string INFNFE_IDE_NFR_RNFP_IE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_SERIE { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_NNF { get; set; }
        public string INFNFE_IDE_NFR_RNFP_RCTE { get; set; }
        public string INFNFE_IDE_NFR_RNFP_RECF_MOD { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_RECF_NECF { get; set; }
        public Nullable<int> INFNFE_IDE_NFR_RNFP_RECF_NCOO { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
    }
}
