//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_NFE_LINHA_IMP_ISSQN
    {
        public int ID { get; set; }
        public int ID_CONTROLE { get; set; }
        public int ID_LINHA { get; set; }
        public Nullable<decimal> TAG_ISSQN_VBC { get; set; }
        public Nullable<decimal> TAG_ISSQN_VALIQ { get; set; }
        public Nullable<decimal> TAG_ISSQN_VISSQN { get; set; }
        public Nullable<int> TAG_ISSQN_CMUNFG { get; set; }
        public Nullable<int> TAG_ISSQN_CLISTSERV { get; set; }
        public string TAG_ISSQN_CSITTRIB { get; set; }
        public System.DateTime DT_CRIACAO { get; set; }
        public int CRIADO_POR { get; set; }
        public System.DateTime DT_ALTERACAO { get; set; }
        public int ALTERADO_POR { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> TAG_VDEDUCAO { get; set; }
        public Nullable<decimal> TAG_VOUTRO { get; set; }
        public Nullable<decimal> TAG_VDESCINCOND { get; set; }
        public Nullable<decimal> TAG_VDESCCOND { get; set; }
        public Nullable<decimal> TAG_VISSRET { get; set; }
        public string TAG_INDISS { get; set; }
        public string TAG_CSERVICO { get; set; }
        public string TAG_CMUN { get; set; }
        public string TAG_CPAIS { get; set; }
        public string TAG_NPROCESSO { get; set; }
        public string TAG_INDINCENTIVO { get; set; }
    }
}
