//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABMC.RANFE.LIGHT_SQL.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RanfeLight_Entities : DbContext
    {
        public RanfeLight_Entities()
            : base("name=RanfeLight_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABMC_RACTE_CONTROLE> ABMC_RACTE_CONTROLE { get; set; }
        public DbSet<ABMC_RACTE_XML_TMP> ABMC_RACTE_XML_TMP { get; set; }
        public DbSet<INT_NFE_CONTROLE> INT_NFE_CONTROLE { get; set; }
        public DbSet<INT_NFE_LINHA> INT_NFE_LINHA { get; set; }
        public DbSet<INT_NFE_LINHA_ARMAS> INT_NFE_LINHA_ARMAS { get; set; }
        public DbSet<INT_NFE_LINHA_COMBUST> INT_NFE_LINHA_COMBUST { get; set; }
        public DbSet<INT_NFE_LINHA_DI> INT_NFE_LINHA_DI { get; set; }
        public DbSet<INT_NFE_LINHA_DI_ADI> INT_NFE_LINHA_DI_ADI { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_COFINS> INT_NFE_LINHA_IMP_COFINS { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_ICMS> INT_NFE_LINHA_IMP_ICMS { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_II> INT_NFE_LINHA_IMP_II { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_IPI> INT_NFE_LINHA_IMP_IPI { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_ISSQN> INT_NFE_LINHA_IMP_ISSQN { get; set; }
        public DbSet<INT_NFE_LINHA_IMP_PIS> INT_NFE_LINHA_IMP_PIS { get; set; }
        public DbSet<INT_NFE_LINHA_MEDIC> INT_NFE_LINHA_MEDIC { get; set; }
        public DbSet<INT_NFE_LINHA_VEIC> INT_NFE_LINHA_VEIC { get; set; }
        public DbSet<INT_NFE_NOTA_AVULSA> INT_NFE_NOTA_AVULSA { get; set; }
        public DbSet<INT_NFE_NOTA_CANA_DEDUC> INT_NFE_NOTA_CANA_DEDUC { get; set; }
        public DbSet<INT_NFE_NOTA_CANA_FORDIA> INT_NFE_NOTA_CANA_FORDIA { get; set; }
        public DbSet<INT_NFE_NOTA_COBR> INT_NFE_NOTA_COBR { get; set; }
        public DbSet<INT_NFE_NOTA_COBR_DUP> INT_NFE_NOTA_COBR_DUP { get; set; }
        public DbSet<INT_NFE_NOTA_EMIT> INT_NFE_NOTA_EMIT { get; set; }
        public DbSet<INT_NFE_NOTA_ENTREGA> INT_NFE_NOTA_ENTREGA { get; set; }
        public DbSet<INT_NFE_NOTA_INF_ADIC> INT_NFE_NOTA_INF_ADIC { get; set; }
        public DbSet<INT_NFE_NOTA_INF_ADIC_CANA> INT_NFE_NOTA_INF_ADIC_CANA { get; set; }
        public DbSet<INT_NFE_NOTA_INF_ADIC_OBSCONT> INT_NFE_NOTA_INF_ADIC_OBSCONT { get; set; }
        public DbSet<INT_NFE_NOTA_INF_ADIC_OBSFISCO> INT_NFE_NOTA_INF_ADIC_OBSFISCO { get; set; }
        public DbSet<INT_NFE_NOTA_INF_ADIC_PROCREF> INT_NFE_NOTA_INF_ADIC_PROCREF { get; set; }
        public DbSet<INT_NFE_NOTA_REFER> INT_NFE_NOTA_REFER { get; set; }
        public DbSet<INT_NFE_NOTA_RETIRADA> INT_NFE_NOTA_RETIRADA { get; set; }
        public DbSet<INT_NFE_NOTA_TOTAIS> INT_NFE_NOTA_TOTAIS { get; set; }
        public DbSet<INT_NFE_NOTA_TRANSP> INT_NFE_NOTA_TRANSP { get; set; }
        public DbSet<INT_NFE_NOTA_TRANSP_REBOQUE> INT_NFE_NOTA_TRANSP_REBOQUE { get; set; }
        public DbSet<INT_NFE_NOTA_TRANSP_VOL> INT_NFE_NOTA_TRANSP_VOL { get; set; }
        public DbSet<INT_NFE_NOTA_TRANSP_VOL_LAC> INT_NFE_NOTA_TRANSP_VOL_LAC { get; set; }
        public DbSet<INT_NFE_ORIGEM_XML> INT_NFE_ORIGEM_XML { get; set; }
        public DbSet<INT_NFE_XML> INT_NFE_XML { get; set; }
        public DbSet<INT_NFE_XML_TMP> INT_NFE_XML_TMP { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<INT_NFE_NOTA_DEST> INT_NFE_NOTA_DEST { get; set; }
    }
}
